version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/
  -source: ./scripts/
    destination: /var/www/
permissions:
  - object: /var/www/
    pattern: "**"
    except:[/var/www/scripts/]
    owner: root
    group: www-data
    mode: 777
    acls: 
      - u:www-data:rwx
      - u:ubuntu:rwX
      - m::r 
    type:
      - directory
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh

