version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/
  - source: ./scripts/
    destination: /var/www/
permissions:
  - object: /var/www/scripts/
    pattern: "**"
    owner: root
    group: www-data
    mode: 777
    acls: 
      - u:www-data:rwx
      - u:ubuntu:rwx
      - m::r 
    type:
      - directory
hooks:
  ApplicationStop:
    - location: ./scripts/deregister_from_elb.sh

