version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/
permissions:
  - object: /var/www/
    pattern: "*"
    owner: root
    group: www-data
    mode: 644
    acls: 
      - u:www-data:rwX 
      - u:ubuntu:rwX 
      - m::r 
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

